version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: gestion_cotizacion_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: allsolutions_root_pass_2026
      MYSQL_DATABASE: gestion_cotizaciones_db
      MYSQL_USER: allsolutions_user
      MYSQL_PASSWORD: allsolutions_pass_2026
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  app-backend:
    build: .
    container_name: gestion_cotizacion_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NODE_ENV: production
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_USER: allsolutions_user
      DB_PASSWORD: allsolutions_pass_2026
      DB_NAME: gestion_cotizaciones_db
    depends_on:
      - mysql-db

volumes:
  mysql_data:
